### ISSUE TITLE
Pourquoi inventer un nouveau langage de markup?

### ISSUE THREAD

**Issue by Lapin0t** [corbane/ND-Briques-Numeriques#2]
Je me demande sérieusement à quoi sert le fichier `1-OpenSchema/Formatage des données écrites.md`. C'est selon moi totalement contreproductif et anti liberté des données de vouloir inventer un nouveau langage pour représenter l'information alors que ce n'est pas ça qui manque et que ce n'est à mon sens pas notre objectif principal (alors que c'est un truc hyper compliqué à faire).

Personnellement, je pense que au niveau où se place se qu'on veut construire, il faut être agnostique face à la représentation des données et laisser les choses se faire en mettant l'accent plutôt sur l'interopérabilité.

**Comment by corbane** [comment]
J’ai simplifié ce doc et transformer en une simple proposition
